# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Ejercicios de Astronomia Observacional
author: Sergio Pascual
copyright: "Universidad Complutense de Madrid, 2020-2024"
logo: images/ucm_logo.png

only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context

sphinx:
  config:
    master_doc: index
    language: es
    latex_elements:
        papersize: a4paper
        preamble: |
          \pgfplotsset{compat=1.18}

repository:
  url: https://github.com/sergiopasra/ao-notebooks
  path_to_book: ao_notebooks
  branch: master

launch_buttons:
  binderhub_url: "https://mybinder.org"  

