# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Ejercicios de Astronomia Observacional
author: UCM
logo: images/ucm_logo.png

only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

parse:
  myst_extended_syntax: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: ao2021-problemas.tex

sphinx:
  config:
    language: es
    latex_elements:
        papersize: a4paper
        preamble: |
          \DeclareUnicodeCharacter{03B1}{$\alpha$}
          \DeclareUnicodeCharacter{03B2}{$\beta$}
          \DeclareUnicodeCharacter{03C6}{$\phi$}
          \DeclareUnicodeCharacter{03B4}{$\delta$}
          \DeclareUnicodeCharacter{03B5}{$\epsilon$}
          \DeclareUnicodeCharacter{03BB}{$\lambda$}
          \DeclareUnicodeCharacter{03BC}{$\mu$}
          \DeclareUnicodeCharacter{03B8}{$\theta$}
          \DeclareUnicodeCharacter{03BA}{$\kappa$}
          \DeclareUnicodeCharacter{1D719}{$\phi$}
          \DeclareUnicodeCharacter{2032}{'}
#        babel: |
#          \usepackage[spanish]{babel}


# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

